version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ekomi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outlook_addin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./apps/server
    container_name: ekomi_server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: outlook_addin
      JWT_SECRET: jwt_secret_key
    volumes:
      - ./apps/server:/app

  client:
    build: ./apps/client
    container_name: ekomi_client
    ports:
      - "5173:5173" # or 3001/8080, depending on your dev server
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:3000 # Update based on your setup
    volumes:
      - ./apps/client:/app

volumes:
  postgres_data:

